name: DigitalOcean Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Schamas
        run: npm run prisma

      - name: Build Application
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@main
        with:
          app_name: blogger-api-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
